config/routes.rb
Rails.application.routes.draw do

  resources :mailing_lists, only: [:new, :create, :destroy]
  root "pages#home"
  get "order_page" => "pages#order_page"
  get "confirmation" => "pages#confirmation"
  get "faq" => "pages#faq"
  get "privacy_and_terms" => "pages#privacy_and_terms"
  

end

app/models/mailing_list.rb
class MailingList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mailing_lists_controller.rb
class MailingListsController < ApplicationController


	def new
		@recipient = MailingList.new
	end

	def create
		@recipient = recipient.build(recipient_params)

	    respond_to do |format|
	      if @recipient.save
	        format.html { redirect_to root_path, notice: 'You have successfully been subscribed.' }
	      else
	        format.html { render :new }
	      end
	    end
	end

	private 

	def	recipient_params
		params.require(:mailing_list).permit(:recipient_name, :recipient_email)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def order_page
  end

  def confirmation
  end

  def faq
  end

  def privacy_and_terms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_action_button.html.erb
<br>
<section class="action_button align_center">
	<div class="container">
		<%= link_to "GO", order_page_path, class: "btn btn-lg btn-danger" %>
	</div><!-- end .container -->
</section><!-- end .product_description -->

app/views/layouts/_arrows.html.erb
<span class="vis-xs-block hidden-sm hidden-md hidden-lg">
	<!-- down arrow above -->
	<span class="down-arrow">
		<i class="fa fa-angle-down custom" ></i>
	</span>


	<!-- down arrow below -->
	<span class="up-arrow">
		<i class="fa fa-angle-up custom" ></i>
	</span>
</span>

app/views/layouts/_description.html.erb
<section class="description container text-center">

	<h3>Prepackaged stage management kits, including everything from pencils to "lend" actors to spike tape and a multitool.  We package it. You stage manage.</h3>
	<br>

</section>

app/views/layouts/_footer.html.erb
<br>

<footer class="align_center">
	<div class="container">
		<p>StageManagementSupplies.com is created by <%= link_to 'Virgo Ventures', href: 'http://virgoventures.org/', target: '_none' %>. and owned by a Stage Manager turned Entrepreneur / Web Developer.</p>
		<section class="social_media">
			
			<%= render 'layouts/social_media' %>
			
		</section>
		<p><%= link_to "FAQ", faq_path %> &nbsp;|&nbsp; <%= link_to "Privacy and Terms", privacy_and_terms_path %></p>
		<p>Contact us by emailing Kits@StageManagementSupplies.com</p>
	</div><!-- end .container -->
</footer>

app/views/layouts/_headers.html.erb
<section class="headers">
	<div class="container">
		<h1>Stage Management Kits</h1>

		<h2 class="tagline">We&nbsp;get&nbsp;your&nbsp;gear.&nbsp;  You&nbsp;run&nbsp;the&nbsp;show.</h2>

		<hr class="half">
		<br>
	</div><!-- end .container -->
</section><!-- end .headers section -->

app/views/layouts/_main_images.html.erb
<section class="main_images">

	<div class="row"><!-- row #1 for .main_images -->
		<!-- images are 2448px tall., using the "real illusion" classic filter in Fotor app -->
		<div class="col-xs-4 col-sm-2">
			<%= image_tag 'smkit_1_v2', class: 'img-responsive image' %>
		</div>

		<div class="col-xs-8 col-sm-4">
			<%= image_tag 'smkit_2_v2', class: 'img-responsive image' %>
		</div>	
		
		<div class="col-xs-8 col-sm-4">
			<%= image_tag 'smkit_3_v2', class: 'img-responsive image' %>
		</div>

		<div class="col-xs-4 col-sm-2">
			<%= image_tag 'smkit_4_v2', class: 'img-responsive image' %>
		</div>

	</div><!-- end .row for .main_images -->

</section><!-- end .main_images -->

app/views/layouts/_navbar.html.erb
<!-- bootstrap nav layout -->
  <nav class="navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <h4 class="navbar-brand hidden-xs"><%= link_to 'StageMangagementSupplies.com', root_path %></h4>
      </div><!-- end .navbar-header -->

      <%= render 'layouts/social_media' %>       

    </div><!-- /.container-fluid -->
  </nav>
<!-- bootstrap nav layout -->

app/views/layouts/_newsletter_sign_up.html.erb
<div class="container">
	<!-- Note that clickable button is in navbar partial "Newsletter" link -->
	<div class="modal fade" id="modal-1">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h3 class="modal-heading">SM Supplies Newsletter</h3>
				</div><!-- end .modal-header -->
				<div class="modal-body">
				    TODO: Put Sign up newsletter content here from zoho mailing list service.
				</div><!-- end .modal-body -->
				<div class="modal-footer">
 					TODO: Subscribe button.
				</div><!-- end .modal-footer -->
			</div><!-- end .modal-content-->
		</div><!-- end .modal-dialog -->
	</div><!-- end .modal -->
</div><!-- end .container -->

app/views/layouts/_product_contents.html.erb
<section class="product_contents">
	<div class="container">

		<h4>So what's in it?</h4>
		<br>
		<p class="text-center bigger">120 + items, including:</p>
		<br>
		<div class="row align_center">
			<div class="col-sm-4 col-xs-12">				
				<p class="category_name">For the cast <%= render 'layouts/arrows' %></p>
				<ul class="group1">
					<% FOR_CAST.each do |item| %>
						<li><%= item %></li>
					<% end %>
				</ul>
			</div>
			<div class="col-sm-4 col-xs-12">
				<p class="category_name">For the crew <%= render 'layouts/arrows' %></p>
				<ul class="group2">
					<% FOR_CREW.each do |item| %>
						<li><%= item %></li>
					<% end %>
				</ul>
			</div>
			<div class="col-sm-4 col-xs-12">
				<p class="category_name">For you <%= render 'layouts/arrows' %></p>
				<ul class="group3">
					<% FOR_SM.each do |item| %>
						<li><%= item %></li>
					<% end %>
				</ul>
			</div>
		</div><!-- end .row -->
	</div><!-- end .container -->
</section><!-- end .product_description -->

app/views/layouts/_social_media.html.erb
<section class="social-media-section">

	<ul class="social_media align-right">

		<!-- <li><a type="button" data-toggle="modal" data-target="#modal-1" alt="Newsletter" title="Newsletter">Newsletter</a></li> -->

		<li><%= link_to 'Newsletter', new_mailing_list_path %></li>

		<li><a href="#" alt="Pinterest" title="Pinterest"><%= image_tag 'Pinterest.png' %></a></li>

		<li><a href="#" alt="Instagram" title="Instagram"><%= image_tag 'Instagram.png' %></a></li>

		<li><a href="#" alt="Twitter" title="Twitter"><%= image_tag 'Twitter.png' %></a></li>

		<li><a href="#" alt="Facebook" title="Facebook"><%= image_tag 'Facebook.png' %></a></li>
		
	</ul>

</section><!-- end .social-media-section -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Stage Management Kits</title>
  <!-- (TODO: insert description: Prepackaged stage management kits, including everything from pencils to "lend" actors to spike tape and a multitool.  We package it. You stage manage.) -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway+Dots' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Euphoria+Script' rel='stylesheet' type='text/css'>
  <script src="https://use.fontawesome.com/023f91b6ec.js"></script>
 

</head>
<body class="<%= controller_name %>_<%= action_name%>">

  <%= render 'layouts/newsletter_sign_up' %>
	
	<%= render 'layouts/navbar' %>	

	<%= render 'layouts/headers' %>

	 <%= yield %>
	
	<%= render 'layouts/footer' %>

</body>
</html>

app/views/mailing_lists/new.html.erb
<main id="mailing-list" class="container text-center">
	<h3>Join our mailing list </h3>
	<br>

	<%= form_for(@recipient) do |r| %>
		<div>
			<%= r.label :Your_Full_Name %>
			<%= r.text_field :recipient_name, placeholder: 'Ms. Great Human', class: "form-control" %>
		</div>
		<br>
		<div>
			<%= r.label :Your_Email_Address %>
			<%= r.text_field :recipient_email, placeholder: 'Me@MyGreatness.com', class: "form-control" %>
		</div>
		<br>
		<div>
			<%= r.submit("Join Mailing List", class: 'btn btn-md btn-danger') %>
		</div>

	<% end %>
	<br><br>

</main>

app/views/pages/confirmation.html.erb
<section class="receipt">
	<h3>Your order has been confirmed.</h3>

	<p>Kit Summary:</p>

	<p>Special kit considerations:</p>

	<p>Billing Address:</p>

	<p>Shipping Address:</p>

	<p>Payment:</p>

	<h4>We have sent an email to ___.</h4>

	<h3>Please feel free to email us at Kits@StageManagementSupplies.com with any further inquiries, suggestions, or lovely comments.</h3>

	<h2>Happy Stage Managing!</h2>

</section>

app/views/pages/faq.html.erb
<section class="FAQ white">
	<div class ="container">

		<h3>FAQ:</h3>

		<p class="question">Q: How is my kit packaged?</p>
		<p class="answer">A: Most of your kit is able to come prepackaged in its container. Some packaging material is added for padding purposes, but we try to keep the shipping box as compact as is reasonable.</p>

		<p class="question">Q: What if I want to modify my kit contents?</p>
		<p class="answer">A: You can request minor adjustments during the checkout process.  While compiling your kit, we will try to accomodate your requests, but we can offer no guarantees.  If we cannot make the adjustments you request, we will notify you by email, and continue fulfilling your order.</p>

		<p class="question">Q: Do you have smaller kit packages available?</p>
		<p class="answer">A: We are in the process of developing smaller kit packages for those that are looking to add small collections to their existing kits. To do this, we need your feedback. Please let us know if this is of interest to you by emailing us at Kits@StageManagementSupplies.com.  <br>Thank you in advance for your input.</p>

		<p class="question">Q: Do you offer returns?</p>
		<p class="answer">A: We are sorry, we cannot process returns at this time.</p>

		<p class="question">Additional questions?</p>
		<p class="answer">Email us at Kits@StageManagementSupplies.com for an answer. We may even end up adding the answer to this FAQ section.  If we do, thanks for helping us improve the site for future stage managers and the people that love them.</p>

	</div>

</section>

app/views/pages/home.html.erb
<%= render 'layouts/main_images' %>

<%= render 'layouts/description' %>

<!-- <section id="test-area" class="align-center">
	<p id="click-this"><button class="btn btn-warning">TODO: Erase This Area</button></p>
	<p id="drop-this">This should toggle after clicking above erase area.</p>
</section> -->

<%= render 'layouts/product_contents' %>

<%= render 'layouts/action_button' %>

app/views/pages/order_page.html.erb
<section class="kit_adjustments">
	<p>Are there any adjustments you'd like us to make to your kit? We cannot guarantee any requests, but we will do what we can.</p>
	
	<input></input>
	
</section>

<section class="payment_details gray">
	<div class ="container">
		<h3>Payment Details</h3>
	</div>
</section><!-- end .payment_details -->

<section class="shipping_details white">
	<div class ="container">
		<h3>Shipping Details</h3>

		<p>We offer free shipping in the US.</p>
		Checkbox: I am shipping outside the USA. 
		JQuery: drop down add payment method and ruby addition to cost to update payment method</p>
	</div>
</section><!-- end .shipping_details -->


<section class="order_summary gray">
	<div class ="container">
		<h3>Order Summary</h3>
	</div>
</section><!-- end .order_summary -->

<section class="action_button align_center">
	<br>
	<button class="btn btn-lg btn-danger">Complete Order</button>
</section><!-- end .action_button -->

app/views/pages/privacy_and_terms.html.erb
<section class="privacy gray">
	<div class="container">

		<h3>Privacy Policy</p>

		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

	</div>
</section><!-- end .privacy -->

<section class="terms white">
	<div class="container">
		<h3>Terms and Conditions</h3>

		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

	</div>
</section><!-- end .terms -->